# Site settings
title: Athena
subtitle: A framework for defending machine learning adersarial attacks
description: |
    Athena is a framework for defending machine learning adersarial attacks. 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://softsys4ai.github.com/athena" # the base hostname & protocol for your site
githubdir: "softsys4ai/athena"

# Author/user information
email: 
twitter_username: 
github_username:  softsys4ai
authorurl: "https://softsys4ai.github.com/athena"
address: |
    550 Assembly Street
    Columbia, SC 29205


# Build settings
markdown: kramdown

# Other options
permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css']
exclude: ['data', 'docs', 'notebooks', 'references', 'reports', 'scripts', 'src', 'tests']
# SEO stuff
# google_author: ""
# google_site_verification: ""
# bing_webmastertools_id: ""
