# Site settings
title: Athena
subtitle: A Framework for Defending Machine Learning Systems against Adversarial Attacks
description: |
    Athena is a framework for defending machine learning adersarial attacks. 
baseurl: "/athena" # the subpath of your site, e.g. /blog/
url: "https://softsys4ai.github.io" # the base hostname & protocol for your site
githubdir: "softsys4ai/athena"

# Author/user information
email: 
twitter_username: 
github_username:  softsys4ai
authorurl: "https://softsys4ai.github.io/athena/"
address: |
    550 Assembly Street
    Columbia, SC 29205

# Build settings
markdown: kramdown

# Other options
permalink: /:year-:month-:day-:title/
#permalink: blog/:year/:month/:title
excerpt_separator: "<!--more-->"

include: ['_images', '_css'] #, '_sass', '_includes',]
exclude: ['data', 'docs', 'notebooks', 'references', 'reports', 'scripts', 'src', 'tests', 'Makefile', 'requirements.txt', 'setup.py']
