# Site settings
title: ATHENA
subtitle: A Framework based on Diverse Weak Defenses for Building Adversarial Defense
authors: Ying Meng*, Jianhai Su, Jason M O'Kane, Pooyan Jamshidi*
lab: softsys4ai
email: ymeng@email.sc.edu
description: |
  ATHENA is a framework for building adversarial defense.
baseurl: "/athena" # the subpath of your site, e.g. /blog/
url: "https://softsys4ai.github.io" # the base hostname & protocol for your site
githubdir: "softsys4ai/athena"
#theme: jekyll-theme-clean-blog

# Publish posts or collection documents with a future date.
#future: true

# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: /:year-:month-:day-:title/ #pretty
#paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md","README.zh.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
# If you have timezone issue (e.g. #68) in China, uncomment to use this:
#timezone: CN  

# Gems
# from PR#40, to support local preview for Jekyll 3.0
# make sure you have this gem installed
# `$ gem install jekyll-paginate`
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1

# Sidebar settings
sidebar: false

# Featured Tags
featured-tags: false                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value

# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true

# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: true
